############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Blog"
weight = 2
pageRef = "/blog"

[[main]]
name = "About"
pageRef = "/about"
weight = 3

[[main]]
name = "Contact"
pageRef = "/contact"
weight = 4

# [[main]]
# parent = "Pages"
# name = "Blog"
# pageRef = "/blog"

# [[main]]
# parent = "Pages"
# name = "Contact"
# pageRef = "/contact"

# [[main]]
# parent = "Pages"
# name = "Authors"
# pageRef = "/authors"

# [[main]]
# parent = "Pages"
# name = "Categories"
# pageRef = "/categories"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# pageRef = "/404"


# footer menu
[[footer]]
name = "Term of Uses"
pageRef = "/privacy-policy"
weight = 3

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3

[[footer]]
name = "Disclaimer"
pageRef = "/privacy-policy"
weight = 4

